apiVersion: builds.katanomi.dev/v1alpha1
kind: Build
spec:
  git:
    options:
      depth: 1
      timeout: 10m
      retries: 0
      resources:
        limits:
          cpu: 200m
          memory: 200Mi
        requests:
          cpu: 200m
          memory: 200Mi
  templates:
    - templateRef:
        resolver: katanomi.dev.clustertemplate
        params:
          - name: name
            value: go-build-v1
      params:
        - name: tool-image
          value: registry.alauda.cn:60080/devops/builder-go:latest
        - name: test-quality-gate
          value: "false"
        - name: sonar-server
          value: https://build-sonar.alauda.cn
        - name: container-images
          value:
            - build-harbor.alauda.cn/ait/ait/machine-controller:$(build.git.lastCommit.shortID)
